- hosts: all
  tasks:
    - name: subir script a la maquina
      copy:
        dest: /home/user
        src: trinity.sh
        backup: no
        mode: u=rwx,g=rx,o=rx
      become: yes
    
    - name: run script
      shell: ./trinity.sh
      become: yes

